xynehq/xyne

docs/mint.json

hopefully this will fix the bug of redirect, can only test this in production

docs: redirect for introduction

---

docs/mint.json

Revert "docs: redirect for introduction"

---

server/integrations/google/gmail-worker.ts

Updated `gmail-worker ` code to update gmail attachment stats at ingestion for `service-account`.
Can test with service account while ingestion to see attachment stats are correctly updated.

fix(ingestion-stats): Add missing gmail attachment stats for service-account

---

renovate.json

I want renovate to be able to create PR's but don't want it to autoclose them.

fix(renovate): prevent auto close of PR's by renovate bot

---

server/config.ts
server/logger/index.ts

This PR introduces a modification to the logging behavior based on the environment.
Logs are printed in a single-line format for better readability and performance.
Logs are printed in a multi-line format to enhance debugging and traceability.
index.ts: Adjusted to check the environment variable before passing the appropriate logger object responsible for printing the logs.
Tested Locally
None so far

Logs formatting

---

server/ai/mappers.ts
server/ai/provider/bedrock.ts
server/ai/provider/index.ts
server/ai/types.ts
server/api/admin.ts
server/config.ts
server/db/connector.ts
server/db/user.ts

When we detect reasoning case for AWS, we turn their api back to <think> </think> tags.
Also we fixed a bug where OAuth connectors were not scoped per user.
tested locally

Allow deep seek like reasoning and fix connectors to be per user

---

server/api/admin.ts
server/api/oauth.ts
server/db/oauthProvider.ts

First issue was connectors were not scoped per user.
Now once we fetch connectors per user we were not doing so for providers.
This caused the connect button to fail for OAuth.
locally

fix(oauth): Make oauth providers per user

---

server/types.ts

Server would not reach debug mode even though the frontend is in that so we would get less match features.
tested locally

fix(debug): allow server match features in debug mode

---

server/api/admin.ts
server/api/agent/promptGeneration.ts
server/api/search.ts
server/integrations/google/fetch_drive_client.ts
server/integrations/google/index.ts
server/server.ts

chore: format the code

---

server/api/search.ts

fixed build, removed isAtSearch argument

---

server/api/chat/agents.ts

Spanning and cost calculation for jaf implementation in xyne

fix for ragSpan

---

server/db/schema/workspaces.ts
server/db/seed.ts
server/db/workspace.ts

Demo: 
https://github.com/user-attachments/assets/269f47b5-7442-488d-ae3b-36562dc4e7e0

organisation-user-etc-integration-from-bose-to-xyne

---

server/ai/provider/vertex_ai.ts
server/api/chat/agents.ts
server/api/chat/chat.ts

wrong model id getting passed issue fixed
tested locally.

fix: model issues

---

frontend/src/components/workflow/api/ApiHandlers.ts

Cors issue fixes

---

frontend/src/components/workflow/WorkflowBuilder.tsx
frontend/src/routes/_authenticated/workflow.tsx
server/server.ts

Workflow route issue fix and removed logs Hotfix

---

server/api/files.ts
server/api/knowledgeBase.ts

Fixed file content retrieval: used wrong format for names

---

frontend/src/components/CitationPreview.tsx
frontend/src/routes/_authenticated/chat.tsx

- added back button in citation preview
- tested locally

fix(citation preview): added back button in citation preview

---

server/types.ts

replace z.instanceof(File) with z.any()  for better compability

fix(fileUpload) : replace z.instanceof(File) with z.any() 

---

deployment/portable/deploy.sh
deployment/portable/docker-compose.app.yml
deployment/portable/docker-compose.infrastructure-cpu.yml
deployment/portable/docker-compose.infrastructure.yml
deployment/portable/vespa-deploy/Dockerfile
server/vespa/deploy-docker.sh

corrected Vespa deploy.sh exectution dependency

Uat server fix

---

server/ai/agentPrompts.ts
server/services/fileProcessor.ts

fix: document chat prompt is fixed (#898)

---

frontend/src/components/DocumentChat.tsx
frontend/src/components/PdfViewer.tsx
frontend/src/hooks/useChatStream.ts
server/api/chat/chat.ts
server/db/chat.ts
server/db/schema/chats.ts

* fix: fixed history model to not show document chats
* fix: renamed documentChat to kbChat
* fix: renamed sources to kbitems
* fix: added same changes to retry api
* fix: replaced boolean with enum for scaling

fix: fixed history model to not show document chats (#910)

---

frontend/src/components/ChatBox.tsx

chatBox input issue
tested loaclly.

fix: chatBox input disappearing on enter when streaming (#918)

---

frontend/src/routes/_authenticated/knowledgeManagement.tsx

fix(documentChatUI): fixed DocumentChatUI width issue (#932)

---

frontend/src/components/workflow/OnFormSubmissionUI.tsx
frontend/src/components/workflow/WorkflowBuilder.tsx
frontend/src/components/workflow/WorkflowExecutionModal.tsx
frontend/src/components/workflow/executedWorkflowRenderer.tsx

fix(workflow-builder-UI): auto-zoom-img-support-removal

---

server/scripts/clear-workflow-data.ts

feat(workflow): clear workflow data

---

frontend/src/components/workflow/AIAgentConfigUI.tsx

fix-model-list

---

frontend/src/assets/empty-state.svg
frontend/src/components/workflow/WorkflowBuilder.tsx
frontend/src/components/workflow/WorkflowExecutionsTable.tsx
frontend/src/components/workflow/WorkflowIcons.tsx
frontend/src/routes/_authenticated/workflow.tsx

empty-state-improve
